### ISSUE TITLE
Add feature to init web-ui via api (username, powerdns)

### ISSUE THREAD

**Issue by Syntax3rror404** [PowerDNS-Admin/PowerDNS-Admin#1080]
Hello, I need the possibility to create a user via api and enter the powerdns in the ui, because we roll out powerdns automatically with ansible

**Comment by jbe-dw** [comment]
Hello,

In my ansible role I create the admin user directly into the database. There is no way to do it now. A PR is welcome.

**Comment by Syntax3rror404** [comment]
@jbe-dw how you made that? What is with the configuration to the powerdns server api?

**Comment by jbe-dw** [comment]
A few call to community.mysql.mysql_query to check if the user exists and that the password matches the one provided in the playbook.

You can use the same strategy to initiate the settings, like external authentication.

**Comment by Syntax3rror404** [comment]
Thanks :) Yes I know this collection, but i don't know which tables in the database I have to use for this action. Can you share your code snippet for the user?

**Comment by jbe-dw** [comment]
Nope this database is for PowerDNS not PowerDNS Admin. If you don't have it it's probably in a sqlite file.

```
- name: Init the Administrator User
  block:
    - name: Check if Admin account exists
      community.mysql.mysql_query:
        query: "SELECT * FROM user WHERE username='{{ admin_username }}';"
      register: mysql_users

    - name: Create Admin account
      community.mysql.mysql_query:
        query: >-
          INSERT INTO user(username, password, firstname, lastname, email, otp_secret, role_id, confirmed)
          VALUES(%s, %s, 'PowerDNS', 'Admin', 'powerdns.admin@localhost', NULL, 1, 0);
        positional_args:
          - "{{ admin_username }}"
          - "{{ admin_password | password_hash('bcrypt') }}"
      when: mysql_users.rowcount[0] == 0

    - name: Check if Admin password match
      set_fact:
        password_match: "{{ admin_password | password_clear_check(mysql_users.query_result[0][0]['password']) }}"
      when: mysql_users.rowcount[0] == 1

    - name: Update Admin password
      community.mysql.mysql_query:
        query: >-
          UPDATE user set password='{{ admin_password | password_hash('bcrypt') }}'
          WHERE username='{{ admin_username }}' AND id={{ mysql_users.query_result[0][0]['id'] }};
      when: mysql_users.rowcount[0] == 1 and not password_match
```
It needs a custom filter password_clear_check which validates that a text string matches a bcrypt hash.

```
#!/usr/bin/python
import bcrypt

class FilterModule(object):
    def filters(self):
        return {
            'password_clear_check': self.password_clear_check
        }

    def password_clear_check(self, clear_password, hashed_password):

        if bcrypt.hashpw(clear_password.encode('utf-8'), hashed_password.encode('utf-8')) == hashed_password.encode('utf-8'):
            return True
        else:
            return False
```
