### ISSUE TITLE
BUG: Values for fields in database (PostgreSQL) False/True not actual boolean?

### ISSUE THREAD

**Issue by emollusion** [PowerDNS-Admin/PowerDNS-Admin#1240]
Hi!

Trying to make an ansible role to deploy this automatically configuring PowerDNS-Admin in it entirety.
I came across examples where the values in the database, provided as booleans, does not seem to be provided as booleans in all cases, and neither retrieved as booleans in all cases, this behaviour was not expected and hence submitting this as a bug.
Happy to discuss the method behind it and put this as a feature request instead perhaps.

In table "setting" I wanted to disable the OTP field, from ansible I asked it to set one row as the following:
id,name,value
7,otp_field_enabled,False

This is translated by PostgreSQL as a boolean value and the actual literal value becomes "false".
When accessing the setting in the GUI, this setting is an on/off switch usually, but has now turned into a text field with the value "false".
Altering the text field to "False" and submitting, changes the setting back to an on/off switch and alters the value in the database to "False".

The same pattern follow a series of other settings as well, namely (but not limited to):
 6 | signup_enabled             | False
 23 | autoprovisioning           | False
 26 | purge                      | False

Is this all by design or has just no one else come across it?

**Comment by jbe-dw** [comment]
Hello,

Thanks for the feedback. I guess that it has not been implemented correctly. This is not really a bug, because you put something in the database outside PDA. But it's right to point that it should use real booleans.

I'd like to work on the API to implement a configuration endpoint (and to implement an init process to be 100% compatible with automation tools). I'll have a look over it then. I can't tell you when, as I'm on my own now, but I'll update this issue later.

Regards

**Comment by emollusion** [comment]
Hi!

Removed the bug prefix.

Great work! A small hickup in the automation so no big deal really, keep it in the pipeline and "fix" it when  possible.
Thank you!

**Comment by jbe-dw** [comment]
With Ansible and MariaDB, I use this: 

```
vars:
__default_pdnsa_settings:
  # General Settings
  allow_user_create_domain: false
  auto_ptr: false
  bg_domain_updates: false
  default_domain_table_size: 10
  default_record_table_size: 15

tasks:
    - name: Task reading all the settings in a loop
      register: pdnsa_current_settings
    - name: Update General settings
      community.mysql.mysql_query:
        login_host: "{{ _pdnsa_config.db_bind_address }}"
        login_port: 3306
        login_user: "{{ _pdnsa_config.db_user }}"
        login_password: "{{ _pdnsa_config.db_password }}"
        login_db: "{{ _pdnsa_config.db_name }}"
        query: >-
          INSERT INTO setting (id, name, value) VALUES
          ({{ pdnsa_current_settings.results[idx].query_result[0][0].id
               if pdnsa_current_settings.results[idx].rowcount[0] > 0
               else 'NULL'
            }}, '{{ setting.key }}', %s)
          ON DUPLICATE KEY UPDATE value = VALUES(value), name = VALUES(name);
       positional_args:
          - >-
            {{ setting.value|join(', ')
            if (setting.value is sequence and setting.value is not string)
            else setting.value|string }}
        loop: "{{_pdnsa_settings|dw.pdnsadmin.dict_filter(pdnsa_default_settings.keys())|dict2items }}"
```
But maybe Postgres behaves differently. You can see on the last line that i'm converting anything to string. 

This is the morning now and my brain is not asleep. I'd say that the table mixes string and boolean values in a shared TEXT column, so booleans are translated to strings. I guess that it was the main reason to do so. There are probably alternatives to organize things differently, but one should check what SQLAlchemy offers.
