### ISSUE TITLE
Expose more settings as environment variables

### ISSUE THREAD

**Issue by phinx110** [PowerDNS-Admin/PowerDNS-Admin#1262]
I am currently trying to configure the entire pdns admin docker using enviroment variables but I'm hitting a wall. It seems like not al the settings that can be configured using the GUI are exposed as settable environment variables.

For [keycloack integration](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/docs/oauth.md) I need to set Client key, Client secret, Scope, API URL, Token URL, Authorize URL, Logout URL, but in [docker_config.py](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/configs/docker_config.py) only OIDC_OAUTH_API_URL, OIDC_OAUTH_TOKEN_URL and OIDC_OAUTH_AUTHORIZE_URL are available.

As for the powerDNS settings like PDNS_HOST, PDNS_API_KEY, PDNS_VERSION I have found mentions in pull-requests https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/286 https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1216 but they also don't seem to work because they are not included inside docker_config.py

In general I see a lot more settings inside [/powerdnsadmin/models/setting.py](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/powerdnsadmin/models/setting.py) than in docker_config.py, that I would like to get my hands on using env vars. 

I've already tried a deployment using the following config inside my k8s cluster:

```
....
      containers:
      ...
      - name: powerdns
        image: powerdns/pdns-auth-46
        ports:
        - name: dns-udp
          protocol: UDP
          containerPort: 5301
        - name: dns-tcp
          protocol: TCP
          containerPort: 5301
        - name: pdns-api
          containerPort: 8081
        volumeMounts:
        - name: powerdns-data
          mountPath: /data
        - name: powerdns-config
          mountPath: /etc/powerdns
      - name: powerdns-admin
        image: ngoduykhanh/powerdns-admin:latest
        ports:
        - containerPort: 80
        env:
        - name: PDNS_HOST
          value: "http://127.0.0.1:8081/"
        - name: PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: powerdns-api-key
              key: key
        - name: PDNS_VERSION
          value: "4.6.3"
        - name: OIDC_OAUTH_API_URL
          value: "https://app.{{ .Values.domain }}/auth/realms/administration/protocol/openid-connect/userinfo"
        - name: OIDC_OAUTH_TOKEN_URL
          value: "https://app.{{ .Values.domain }}/auth/realms/administration/protocol/openid-connect/token"
        - name: OIDC_OAUTH_AUTHORIZE_URL
          value: "https://app.{{ .Values.domain }}/auth/realms/administration/protocol/openid-connect/auth"
        - name: SIGNUP_ENABLED
          value: "false"
        - name: REMOTE_USER_ENABLED
          value: "true"
```
But I could not get keycloack nor the pdns setting to work.

My use case: I have everything already inside k8s secrets (passwords, keys, ids, ...) and would like to mount them as env vars to create a portable/repeatable deployment, to have everything as code and to reduce manual tasks in order to shorten time to deployment when deploying from dev to staging to prod environments and a shorter disaster recovery time. Another use case is that I can rotate all my secrets inside my k8s cluster, then I would only need to restart the pod for it to propagate.
