### ISSUE TITLE
Issues setting up MySQL connection

### ISSUE THREAD

**Issue by MikEarpp** [PowerDNS-Admin/PowerDNS-Admin#1320]
<details>
  <summary>Thank you very much for your sharing</summary>
  
2022-12-10T13:57:24.172481700Z Traceback (most recent call last):
2022-12-10T13:57:24.172554727Z   File "/usr/bin/flask", line 8, in <module>
2022-12-10T13:57:24.172564670Z     sys.exit(main())
2022-12-10T13:57:24.172570075Z   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 967, in main
2022-12-10T13:57:24.172608053Z     cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
2022-12-10T13:57:24.172613922Z   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 586, in main
2022-12-10T13:57:24.172619290Z     return super(FlaskGroup, self).main(*args, **kwargs)
2022-12-10T13:57:24.172624622Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 1055, in main
2022-12-10T13:57:24.172629800Z     rv = self.invoke(ctx)
2022-12-10T13:57:24.172634687Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
2022-12-10T13:57:24.172647229Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2022-12-10T13:57:24.172652343Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
2022-12-10T13:57:24.172657829Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2022-12-10T13:57:24.172662652Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
2022-12-10T13:57:24.172667549Z     return ctx.invoke(self.callback, **ctx.params)
2022-12-10T13:57:24.172672366Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 760, in invoke
2022-12-10T13:57:24.172677254Z     return __callback(*args, **kwargs)
2022-12-10T13:57:24.172700465Z   File "/usr/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
2022-12-10T13:57:24.172705959Z     return f(get_current_context(), *args, **kwargs)
2022-12-10T13:57:24.172711091Z   File "/usr/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
2022-12-10T13:57:24.172716196Z     return __ctx.invoke(f, *args, **kwargs)
2022-12-10T13:57:24.172721198Z   File "/usr/lib/python3.8/site-packages/click/core.py", line 760, in invoke
2022-12-10T13:57:24.172726278Z     return __callback(*args, **kwargs)
2022-12-10T13:57:24.172731224Z   File "/usr/lib/python3.8/site-packages/flask_migrate/cli.py", line 134, in upgrade
2022-12-10T13:57:24.172736286Z     _upgrade(directory, revision, sql, tag, x_arg)
2022-12-10T13:57:24.172741411Z   File "/usr/lib/python3.8/site-packages/flask_migrate/__init__.py", line 96, in wrapped
2022-12-10T13:57:24.172746480Z     f(*args, **kwargs)
2022-12-10T13:57:24.172751392Z   File "/usr/lib/python3.8/site-packages/flask_migrate/__init__.py", line 271, in upgrade
2022-12-10T13:57:24.172756480Z     command.upgrade(config, revision, sql=sql, tag=tag)
2022-12-10T13:57:24.172761402Z   File "/usr/lib/python3.8/site-packages/alembic/command.py", line 322, in upgrade
2022-12-10T13:57:24.172766608Z     script.run_env()
2022-12-10T13:57:24.172771431Z   File "/usr/lib/python3.8/site-packages/alembic/script/base.py", line 569, in run_env
2022-12-10T13:57:24.172785198Z     util.load_python_file(self.dir, "env.py")
2022-12-10T13:57:24.172791906Z   File "/usr/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
2022-12-10T13:57:24.172797223Z     module = load_module_py(module_id, path)
2022-12-10T13:57:24.172802034Z   File "/usr/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
2022-12-10T13:57:24.172807077Z     spec.loader.exec_module(module)  # type: ignore
2022-12-10T13:57:24.172811925Z   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2022-12-10T13:57:24.172817027Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-12-10T13:57:24.172822118Z   File "migrations/env.py", line 88, in <module>
2022-12-10T13:57:24.172827152Z     run_migrations_online()
2022-12-10T13:57:24.172831941Z   File "migrations/env.py", line 68, in run_migrations_online
2022-12-10T13:57:24.172836851Z     engine = engine_from_config(config.get_section(config.config_ini_section),
2022-12-10T13:57:24.172841795Z   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 543, in engine_from_config
2022-12-10T13:57:24.172846848Z     return create_engine(url, **options)
2022-12-10T13:57:24.172851690Z   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 500, in create_engine
2022-12-10T13:57:24.172856863Z     return strategy.create(*args, **kwargs)
2022-12-10T13:57:24.172861648Z   File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
2022-12-10T13:57:24.172866631Z     dbapi = dialect_cls.dbapi(**dbapi_args)
2022-12-10T13:57:24.172871500Z   File "/usr/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
2022-12-10T13:57:24.172876560Z     return __import__("MySQLdb")
2022-12-10T13:57:24.172890833Z ModuleNotFoundError: No module named 'MySQLdb'
  }
  ```
version: '3.9'
  networks:
    minette:
      external: true
      internal: false
    nonette:
      external: true
      internal: true
services:

  pdns_admin:
    container_name: pdns_admin
    env_file:
      - .env
      - .env_mysql_pdns
    environment:
      SQLALCHEMY_DATABASE_URI: mysql://${_MYSQL_USER}:${_MYSQL_PASS}@${_NO_INTERNET_SUBNET_IP}${_MARIADB_IP}:${_MARIADB_PORT}/${_MYSQL_DB}
      GUNICORN_LOGLEVEL: DEBUG
    #image: ngoduykhanh/powerdns-admin:latest
    image: ngoduykhanh/powerdns-admin:v0.3.0
    networks:
      minette:
        ipv4_address: ${_DOCKER_SUBNET_IP}${_PDNS_WEB_IP}
      nonette:
        ipv4_address: ${_NO_INTERNET_SUBNET_IP}${_PDNS_WEB_IP}
    restart: unless-stopped
```
</details>
