### ISSUE TITLE
Domain duplicated when saving

### ISSUE THREAD

**Issue by DedBash** [PowerDNS-Admin/PowerDNS-Admin#1362]
Hello I have the problem that whenever I save my records the main domain behind all record is saved again. have added a test domain to show it better therefore the SOA is also not correct have the problem but with all domains

https://user-images.githubusercontent.com/79027536/213887013-efb54416-c469-421e-a86b-52e5aac55b78.mp4

*doamins that are with @ are not affected but all others are

**Comment by AzorianMatt** [comment]
@DedBash could you please tell me exactly what version of the application you are running and in what environment? I.e. Docker or bare metal. If Docker, what is the fully qualified image name that you are running? I am unable to replicate this in the version 0.3.0 release.

**Comment by DedBash** [comment]
I run the whole thing via docker compose with these containers:
![image](https://user-images.githubusercontent.com/79027536/214296057-999ff50d-0310-4a68-82b3-51e3de01e603.png)
And this is my docker-compse.yml (Everything in "[]" is censored for GitHub)
```yml
version: '2'

services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=[DB]
      - MYSQL_USER=[USER]
      - MYSQL_PASSWORD=[KEY]
    ports:
      - 3306:3306
    restart: always
    volumes:
      - /pda-mysql:/var/lib/mysql
  pdns:
    image: pschiffe/pdns-mysql
    hostname: pdns
    domainname: [DOMAIN]
    restart: always
    depends_on:
      - db
    links:
      - "db:mysql"
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
    environment:
      - PDNS_gmysql_host=db
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=[NAME]
      - PDNS_gmysql_dbname=[DB]
      - PDNS_gmysql_password=[KEY]
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=[KEY]
      - PDNSCONF_API_KEY=[KEY]
      - PDNS_webserver=yes
      - PDNS_webserver-allow-from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=[KEY]
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_notify_from=0.0.0.0
      - PDNS_allow_axfr_ips=127.0.0.1

  web_app:
    image: powerdnsadmin/pda-legacy:latest
    container_name: powerdns_admin
    ports:
      - "80:80"
    restart: always
    links:
      - db:mysql
      - pdns:pdns
    logging:
      driver: json-file
      options:
        max-size: 50m
```
