### ISSUE TITLE
New Docker image not starting

### ISSUE THREAD

**Issue by CambridgeComputing** [PowerDNS-Admin/PowerDNS-Admin#1388]
Hello! I am in the middle of testing out a deployment with `MariaDB`, `PowerDNS`, and `PowerDNS-Admin` in a `docker-compose` script. Last night, I had it all working, but today it stopped when I scrapped everything and re-deployed (more testing on my network). If I stay with the previous image (`tag:v0.3.0`), the webapp container comes up fine, but if I try the `tag:latest` (updated on 2/17/2023 it looks like), the container never starts. Below is all I see in the docker logs for the `PowerDNS-Admin` container:
```
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
```

Docker then creates a new container in the swarm and fails again.

Below is my sanitized `docker-compose.yml` file.

```yaml
version: '3.6'

services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=powerdnsadmin
      - MYSQL_USER=pdns
      - MYSQL_PASSWORD=mypdns
    # ports:
    #   - 3306:3306
    restart: always
    volumes:
      - db:/var/lib/mysql

  app:
    image: pschiffe/pdns-mysql
    hostname: pdns
    restart: always
    depends_on:
      - db
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8084:8081
    environment:
      - PDNS_gmysql_host=db
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=pdns
      - PDNS_gmysql_dbname=powerdnsadmin
      - PDNS_gmysql_password=mypdns
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=secret
      - PDNSCONF_API_KEY=secret
      - PDNS_webserver=yes
      - PDNS_webserver-allow-from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.168.1.0/24
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret2
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_notify_from=0.0.0.0
      - PDNS_allow_axfr_ips=127.0.0.1

  web_app:
    image: powerdnsadmin/pda-legacy:latest
    ports:
      - 8083:80
    depends_on:
      - app
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://pdns:mypdns@db/powerdnsadmin
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
```

With the above file in my environment, the db and app containers start up fine, just the web_app container fails. If i switch out `powerdnsadmin/pda-legacy:latest` for `powerdnsadmin/pda-legacy:v0.3.0`, then the web_app container starts without any issue.

Edit: Also, I'm happy to troubleshoot further, I'm just not sure how to collect any info beyond the docker logs above.
