### ISSUE TITLE
PowerDNS-Admin 0.4.0 - Microsoft OAuth Broken

### ISSUE THREAD

**Issue by gbe0** [PowerDNS-Admin/PowerDNS-Admin#1430]
Hi,

Existing release: 0.3.0
Deployment method: Docker
Old container: `powerdnsadmin/pda-legacy:v0.3.0`
New container: `powerdnsadmin/pda-legacy:v0.4.0`
Database: MariaDB 10.6

I just gave the new PowerDNS-Admin 0.4.0 release a try but it seems like Microsoft OAuth stops working. After login when AAD redirects back to the Azure handler for PowerDNS-Admin the server shows a 500 error. The following exception is logged:

```
powerdns_admin    | [2023-03-11 16:07:57,379] [app.py:1449] ERROR - Exception on /azure/authorized [GET]
powerdns_admin    | Traceback (most recent call last):
powerdns_admin    |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
powerdns_admin    |     response = self.full_dispatch_request()
powerdns_admin    |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
powerdns_admin    |     rv = self.handle_user_exception(e)
powerdns_admin    |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
powerdns_admin    |     rv = self.dispatch_request()
powerdns_admin    |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
powerdns_admin    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
powerdns_admin    |   File "/app/powerdnsadmin/services/azure.py", line 35, in azure_authorized
powerdns_admin    |     token = azure.authorize_access_token()
powerdns_admin    |   File "/usr/lib/python3.10/site-packages/authlib/integrations/flask_client/apps.py", line 105, in authorize_access_token
powerdns_admin    |     userinfo = self.parse_id_token(token, nonce=state_data['nonce'], claims_options=claims_options)
powerdns_admin    |   File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 66, in parse_id_token
powerdns_admin    |     claims = _jwt.decode(
powerdns_admin    |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
powerdns_admin    |     data = self._jws.deserialize_compact(s, load_key, decode_payload)
powerdns_admin    |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
powerdns_admin    |     algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
powerdns_admin    |   File "/usr/lib/python3.10/site-packages/authlib/jose/rfc7515/jws.py", line 254, in _prepare_algorithm_key
powerdns_admin    |     key = key(header, payload)
powerdns_admin    |   File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 38, in load_key
powerdns_admin    |     jwk_set = JsonWebKey.import_key_set(self.fetch_jwk_set())
powerdns_admin    |   File "/usr/lib/python3.10/site-packages/authlib/integrations/base_client/sync_openid.py", line 14, in fetch_jwk_set
powerdns_admin    |     raise RuntimeError('Missing "jwks_uri" in metadata')
powerdns_admin    | RuntimeError: Missing "jwks_uri" in metadata
```

The Docker Compose file I am using only has the basics in it:

```yaml
---
version: '3.6'

services:

  powerdns-admin:
    image: powerdnsadmin/pda-legacy:v0.4.0
    container_name: powerdns_admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://powerdns_admin:my-pass@host.docker.internal/powerdns_admin
      - GUNICORN_TIMEOUT=60
      - LOCAL_DB_ENABLED=false
```

If I enable local authentication and take a look at the settings in the admin area they seem to all be fine.

Here is what the working configuration (on the 0.3.0 release as I rolled back) looks like:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/47361208/224501329-eade14f2-a993-4125-84b8-4becaecc3e09.png">
