### ISSUE TITLE
Sessions table replication issue.

### ISSUE THREAD

**Issue by greenaar** [PowerDNS-Admin/PowerDNS-Admin#1443]
Column 1 of table 'powerdns.sessions' cannot be converted from type 'varchar(765(bytes))' to type 'varchar(1020(bytes) utf8mb4)'

This occurs on the database servers replicating from the primary, and stops replication.  As far as I'm aware, all values in that table were created when running the new version for the first time.

Poweradmin shares a database with PDNS in this case.

**Comment by greenaar** [comment]
The compose file I'm using (masked of course)

`services:
  pdns-admin-uwsgi:
    image: pschiffe/pdns-admin-uwsgi
    networks:
      pdns:
        aliases:
          - pdns-admin-uwsgi
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_ADMIN_SQLA_DB_HOST='X.X.X.46'
      - PDNS_ADMIN_SQLA_DB_USER='pdns'
      - PDNS_ADMIN_SQLA_DB_PASSWORD='pdns'
      - PDNS_ADMIN_SQLA_DB_NAME='powerdns'
      - PDNS_VERSION=4.7
      - PDNS_API_KEY=MYSECRET
      - PDNS_API_URL=http://X.X.X.66:8081/
    restart: always
  pdns-admin-static:
    image: pschiffe/pdns-admin-static
    ports:
      - '80:80'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - pdns-admin-uwsgi
    networks:
      - pdns
    links:
      - pdns-admin-uwsgi
    restart: always`

**Comment by greenaar** [comment]
Using mysql: Server version: 8.0.32-0ubuntu0.22.04.2 (Ubuntu)
Session table: 
```
mysql> show create table sessions \G
*************************** 1. row ***************************
       Table: sessions
Create Table: CREATE TABLE `sessions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `session_id` varchar(255) DEFAULT NULL,
  `data` blob,
  `expiry` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `session_id` (`session_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb3
1 row in set (0.00 sec)
```

**Comment by AzorianMatt** [comment]
@greenaar so I found the first issue at least. As I suspected, you're running a third-party Docker image (`pschiffe/pdns-admin-static`) which we obviously can not offer support for. When you had mentioned the environment variable issue on Reddit, it rang a memory bell as I used to use these images as well.

Given that we just released version 0.4.0, I highly doubt the image you're using has even been brought up-to-date. Please consider using the `piwerdnsadmin/pda-legacy` image as a starting point for your deployment.

Thanks!

**Comment by jbe-dw** [comment]
Hello,

We don't support scenarios where you use a single database to host PDA's data and something else, as it adds some restrictions at the database level that can impact all tables.

Can you try to host PDA's data in its own database first ?

Regards

**Comment by greenaar** [comment]
> @greenaar so I found the first issue at least. As I suspected, you're running a third-party Docker image (`pschiffe/pdns-admin-static`) which we obviously can not offer support for. When you had mentioned the environment variable issue on Reddit, it rang a memory bell as I used to use these images as well.
> 
> Given that we just released version 0.4.0, I highly doubt the image you're using has even been brought up-to-date. Please consider using the `piwerdnsadmin/pda-legacy` image as a starting point for your deployment. Not that I think it's necessarily relevant to the weird replication issue FYI, but to address other potential issues with dependencies.
> 
> Thanks!

The issue occurred after switching from the third-party image to pda-legacy, otherwise I agree, it would not be appropriate to ticket it here.

**Comment by AzorianMatt** [comment]
@greenaar so that makes me wonder if the third party image had already made modifications to the source to utilize database sessions. That would explain why it appears that the table already existed but with a different configuration seemingly.

I'm fairly certain that project does make other changes to the source code to facilitate some of the features provided by the image. I used to use an earlier version of theirs for that very reason, which is why I plan to adopt many of those convenience features into the official image.

**Comment by greenaar** [comment]
Ok, new (empty) database.

```
powerdns_admin  | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
powerdns_admin  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
powerdns_admin  | INFO  [alembic.runtime.migration] Running upgrade  -> 787bdba9e147, Init DB
powerdns_admin  | INFO  [alembic.runtime.migration] Running upgrade 787bdba9e147 -> 59729e468045, Add view column to setting table
powerdns_admin  | INFO  [alembic.runtime.migration] Running upgrade 59729e468045 -> 1274ed462010, Change setting.value data type
powerdns_admin  | INFO  [alembic.runtime.migration] Running upgrade 1274ed462010 -> 4a666113c7bb, Adding Operator Role
powerdns_admin  | INFO  [alembic.runtime.migration] Running upgrade 4a666113c7bb -> 31a4ed468b18, Remove all setting in the DB
powerdns_admin  | INFO  [alembic.runtime.migration] Running upgrade 31a4ed468b18 -> 654298797277, Upgrade DB Schema
powerdns_admin  | INFO  [alembic.runtime.migration] Running upgrade 654298797277 -> 0fb6d23a4863, Remove user avatar
powerdns_admin  | INFO  [alembic.runtime.migration] Running upgrade 0fb6d23a4863 -> 856bb94b7040, Add comment column in domain template record table
powerdns_admin  | INFO  [alembic.runtime.migration] Running upgrade 856bb94b7040 -> b0fea72a3f20, Update domain serial columns type
powerdns_admin  | INFO  [alembic.runtime.migration] Running upgrade b0fea72a3f20 -> 3f76448bb6de, Add user.confirmed column
powerdns_admin  | ERROR [root] Error: All MySQL CHANGE/MODIFY COLUMN operations require the existing type.
powerdns_admin exited with code 1
```

My compose file:
```
version: "3"

services:
  app:
    image: powerdnsadmin/pda-legacy:latest
    container_name: powerdns_admin
    ports:
      - "9199:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://pda:pda@172.16.2.xxx/pda
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=INFO
      - SECRETKEY=secret
```

**Comment by greenaar** [comment]
Ok. Dev version is a go.

Note, i did have to pin the docker image to a network range, and whitelist that range for use with the powerdns webserver.  Failing to do that results in an ambiguous error which is actually 'permission denied'.

Final compose file looks like this:
```
version: "3"
services:
  app:
    image: powerdnsadmin/pda-legacy:dev
    container_name: powerdns_admin
    ports:
      - "9199:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://pda:pda@172.16.2.xx/pda
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=INFO
      - SECRETKEY=secret
    networks:
      - pdns

networks:
  pdns:
    ipam:
      config:
        - subnet: 172.16.98.0/24
          gateway: 172.16.98.1
```

with `webserver-allow-from` set to include that ip block in the powerdns configs.  Worth making a note of that perhaps.

I'll watch for dev -> latest/version tag, then i think i'll actually cut over.  All operations worked as expected, including account creation, api config, and record editing.  Slaves replicate successfully.

You are welcome to close this ticket at your convenience.
