### ISSUE TITLE
Unable to open database files?

### ISSUE THREAD

**Issue by WestFarmer** [PowerDNS-Admin/PowerDNS-Admin#1670]
### PDA version

0.4.1

### Python version

3.0

### Steps to Reproduce

```
name: pdns-admin
image: powerdnsadmin/pda-legacy
env:
- name: OFFLINE_MODE
  value: "true"

resources:
requests:
  memory: "128Mi"
  cpu: "200m"
limits:
  memory: "512Mi"
  cpu: "500m"
volumeMounts:
- mountPath: /data
  name: pdns-admin-pv
```

a kubernetes PV is mounted /data.

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

### Expected Behavior

can start up normally

### Observed Behavior

can't start up
