### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by Fossil01** [PowerDNS-Admin/PowerDNS-Admin#727]
Getting this error when running with docker-compose:

pdnsadmin    | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

My compose file:

```yaml
version: "3"
services:
  pdnsadmin:
    container_name: pdnsadmin
    image: ngoduykhanh/powerdns-admin:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "9191:80"
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///data/pdnsadmin.db
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
    # Volumes store your data between container upgrades
    volumes:
      - '/opt/docker/containers/powerdns-admin/data:/data'
    restart: unless-stopped
    user: "0"
    networks:
      - REMOVED

networks:
  REMOVED:
    external:
      name: REMOVED
```

This dir exists: /opt/docker/containers/powerdns-admin/data

What am I doing wrong?
